[package]
name = "aidol"
version = "0.1.4"
description = "AIDOL 角色設計工作室"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
serde_json = "1"
url = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
