import { useEffect, useRef, useState } from 'react';
import { Plus, Minus, CornersOut } from '@phosphor-icons/react';
export function ImagePreview({ asset, title }) {
  const [zoom, setZoom] = useState(1), [ratio, setRatio] = useState(1), [size, setSize] = useState({width: 700, height: 580});
  const stage = useRef(null), drag = useRef(null);
  useEffect(() => { setZoom(1); const observer = new ResizeObserver(entries => { const rect = entries[0].contentRect; setSize({ width: rect.width, height: rect.height }); }); observer.observe(stage.current); return () => observer.disconnect(); }, [asset.id]);
  const width = Math.min(size.width, size.height * ratio) * zoom, height = width / ratio;
  return <div className="image-viewer"><div className="image-viewer-tools"><span>拖曳移動，放大檢查細節</span><button type="button" className="icon-btn" aria-label="縮小圖稿" disabled={zoom <= 1} onClick={() => setZoom(value => Math.max(1, value - .5))}><Minus size={18} /></button><span>{Math.round(zoom * 100)}%</span><button type="button" className="icon-btn" aria-label="放大圖稿" disabled={zoom >= 4} onClick={() => setZoom(value => Math.min(4, value + .5))}><Plus size={18} /></button><button type="button" className="icon-btn" aria-label="圖稿適合視窗" onClick={() => setZoom(1)}><CornersOut size={18} /></button></div><div className="image-viewer-stage" ref={stage} onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); drag.current = { x: event.clientX, y: event.clientY, left: stage.current.scrollLeft, top: stage.current.scrollTop }; }} onPointerMove={event => { if (drag.current) { stage.current.scrollLeft = drag.current.left - event.clientX + drag.current.x; stage.current.scrollTop = drag.current.top - event.clientY + drag.current.y; } }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><div className="image-viewer-size" style={{width: Math.max(size.width, width), height: Math.max(size.height, height)}}><img src={asset.url} alt={title} draggable="false" style={{width, height}} onLoad={event => setRatio(event.currentTarget.naturalWidth / event.currentTarget.naturalHeight)} /></div></div></div>;
}
